version: "3.8"
services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - NODE_ENV=production

  typebot:
    image: ghcr.io/typebot/typebot:latest
    container_name: typebot
    ports:
      - "3000:3000"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: server /data

  deepseek-coder:
    image: openai/deepseek-coder:1.3B
    container_name: deepseek-coder
    ports:
      - "8000:8000"

  f5-tts:
    image: openai/f5-tts
    container_name: f5-tts
    ports:
      - "4000:4000"

  bolt-diy:
    image: boltdiy/boltdiy
    container_name: boltdiy
    ports:
      - "8080:8080"

  nocodb:
    image: nocodb/nocodb
    container_name: nocodb
    ports:
      - "8081:8080"
    environment:
      - NC_DB=sqlite
      - NC_DB_SQLITE_FILENAME=/var/lib/sqlite/nocodb.db
